# Use a imagem oficial do PostgreSQL como base
FROM postgres:latest

# Copie o script init.sql para o diretório /docker-entrypoint-initdb.d/
COPY init.sql /docker-entrypoint-initdb.d/

# Defina as variáveis de ambiente para configurar o PostgreSQL
ENV POSTGRES_DB ServicePro
ENV POSTGRES_USER myuser
ENV POSTGRES_PASSWORD mypassword

# Exponha a porta padrão do PostgreSQL
EXPOSE 5432

# O comando CMD é usado para iniciar o servidor PostgreSQL quando o contêiner for iniciado
CMD ["postgres"]
