version: '3'

services:
  postgres-db:
    image: postgres
    container_name: bancoServicePro
    restart: always
    environment:
      POSTGRES_DB: ServiceProDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ruan123
    ports:
      - '5432:5432'
    volumes:
      - ./volumepostgres:/var/lib/postgresql/data  # Adicionando um volume para o PostgreSQL

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./volumerabbitmq:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456

  servicepro:
    image: ruanfonseca/serviceproimg:latest
    ports:
      - "8080:8080"

  consumer:
    image: ruanfonseca/consumer
    ports:
      - "9191:9191"
