# Use a imagem oficial do OpenJDK como base
FROM openjdk:11

# Diretório de trabalho dentro do contêiner
WORKDIR /app

# Copie o JAR da aplicação para o diretório de trabalho
COPY target/com.ServicePro-0.0.1-SNAPSHOT.jar /app/seu-app.jar

# Exponha a porta que a aplicação Spring Boot está usando (pode variar conforme sua configuração)
EXPOSE 8080

# Comando para executar a aplicação Spring Boot quando o contêiner for iniciado
CMD ["java", "-jar", "seu-app.jar"]
