version: '3'

services:
  postgres-db:
    image: postgres
    container_name: bancoServicePro
    restart: always
    environment:
      POSTGRES_DB: ServiceProDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ruan123
    ports:
      - '5432:5432'
