version: '3'

services:
  postgres-db:
    image: postgres
    container_name: bancoServicePro
    restart: always
    environment:
      POSTGRES_DB: ServiceProDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ruan123
    ports:
      - '5432:5432'
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./dados:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER =admin
      - RABBITMQ_DEFAULT_PASS =123456