@startuml
'https://plantuml.com/sequence-diagram

autonumber

==Verifica lista de requerimentos==

Funcionário -> Sistema: Clicar na opção listar requerimentos projetor
Sistema -> BancoDeDados: Verificar registros de requerimentos
BancoDeDados --> Sistema: Lista de requerimentos encontrados
Sistema -> Funcionário: Exibir lista de requerimentos registrados
== ==




==Verifica detalhes do requerimento==
Funcionário -> Sistema: Clicar na opção detalhes
Sistema -> BancoDeDados: Verificar registros de requerimentos
BancoDeDados --> Sistema: Detalhes do requerimento
Sistema -> Funcionário: Exibir detalhes do requerimento
== ==

==Excluir requerimento==

Funcionário -> Sistema: Clicar na opção excluir
Sistema -> BancoDeDados: Verificar registros de requerimentos
BancoDeDados --> Sistema: Lista de requerimentos
Sistema -> Funcionário: Exibir lista de requerimentos registrados
Funcionário -> Funcionário: Selecionar requerimento a ser excluído
Funcionário -> Sistema: Confirmar exclusão do requerimento
Sistema -> BancoDeDados: Remover requerimento
Sistema -> Funcionário: Exibir mensagem de confirmação de exclusão
== ==


==Edição de requerimento==
Funcionário -> Sistema: Clicar na opção editar
Sistema -> BancoDeDados: Verificar registros de requerimentos
BancoDeDados --> Sistema: Lista de requerimentos
Sistema -> Funcionário: Exibir lista de requerimentos registrados
Funcionário -> Funcionário: Selecionar requerimento a ser editado
Funcionário -> Funcionário: Exibir formulário de edição
Funcionário -> Funcionário: Preencher os campos do formulário
Sistema -> Sistema: Validar os campos preenchidos
Funcionário -> Sistema: Atualizar o requerimento
Sistema -> BancoDeDados: Atualizar o requerimento
BancoDeDados --> Sistema: Confirmação de atualização
Sistema -> Funcionário: Exibir mensagem de confirmação de edição
== ==

==Realizar baixa de requerimento==
Funcionário -> Sistema: Clicar na opção dar baixa
Sistema -> BancoDeDados: Verificar registros de requerimentos
BancoDeDados --> Sistema: Lista de requerimentos
Sistema -> Funcionário: Exibir lista de requerimentos registrados
Funcionário -> Funcionário: Selecionar requerimento a ser dado baixa
Funcionário -> Funcionário: Digitar sua matrícula
Funcionário -> Funcionário: Escrever mensagem de retorno
Funcionário -> Funcionário: Selecionar opção "FINALIZADO"
Funcionário -> Sistema: Registrar requerimento como pendente
Sistema -> BancoDeDados: Atualizar status do requerimento
BancoDeDados --> Sistema: Confirmação de atualização
Sistema -> Funcionário: Exibir mensagem de confirmação de baixa

== ==
@enduml