@startuml
'https://plantuml.com/sequence-diagram

autonumber

== Cadastrar um Requerimento do tipo (PROJETOR) ==
actor Professor


Professor -> Sistema: Autenticação do professor
Sistema -> BancodeDados: Busca no banco de dados da unidade
Sistema -> Professor: Autenticação realizada com sucesso

Professor -> Sistema: Solicitar projetor do campus
Sistema -> Sistema: Exibir formulário correspondente
Professor -> Sistema: Preencher dados do formulário e enviar
Sistema -> Sistema: Realizar validações
Sistema -> BancodeDados: Salvar requerimento
BancodeDados --> Sistema: Confirmação de salvamento
Sistema -> Professor: Exibir mensagem de retorno
== ==



==Submeter requerimento==
Professor -> Sistema: Digitar os dados do formulário e enviar requerimento
Sistema -> Sistema: Realizar a persistência do formulário
== ==

==Persistir Requerimento==
Sistema -> Sistema: Verificar se o requerimento possui todos os campos preenchidos e validados
Sistema -> BancoDeDados: Salvar o requerimento no banco de dados
== ==

==Verificar status do Requerimento (PROJETOR)==
Professor -> Sistema: Digitar o CPF
Sistema -> Sistema: Realizar busca no banco de dados com base no CPF
Sistema -> Professor: Exibir resultados dos requerimentos associados ao CPF
== ==

==Retorno de requerimento==

Sistema -> BancoDeDados: Buscar requerimento utilizando o CPF
BancoDeDados --> Sistema: Requerimento encontrado
Sistema -> Sistema: Retornar o requerimento encontrado
Sistema -> Sistema: Exibir o requerimento encontrado
== ==
@enduml