@startuml
'https://plantuml.com/sequence-diagram

actor Funcionário
actor Sistema

autonumber

==Verifica lista de requerimentos==
Funcionário -> Sistema: Clicar na opção listar requerimentos sala
Sistema -> BancodeDados: Verificar registros de requerimentos
Sistema -> Funcionário: Exibir lista de requerimentos registrados
== ==

==Verifica detalhes do requerimento==
Funcionário -> Sistema: Clicar na opção detalhes
Sistema -> BancodeDados: Verificar detalhes do requerimento
Sistema -> Funcionário: Exibir detalhes do requerimento
== ==


==Excluir requerimento==
Funcionário -> Sistema: Clicar na opção excluir
Sistema -> BancodeDados: Verificar registros de requerimentos
Sistema -> Funcionário: Exibir lista de requerimentos registrados
Funcionário -> Funcionário: Selecionar requerimento a ser excluído
Funcionário -> Sistema: Confirmar exclusão do requerimento
Sistema -> BancodeDados: Remover requerimento
Sistema -> Funcionário: Exibir mensagem de confirmação de exclusão
== ==


==Edição de requerimento==
Funcionário -> Sistema: Clicar na opção editar
Sistema -> BancodeDados: Verificar registros de requerimentos
Sistema -> Funcionário: Exibir lista de requerimentos registrados
Funcionário -> Funcionário: Selecionar requerimento a ser editado
Funcionário -> Funcionário: Exibir formulário de edição
Funcionário -> Funcionário: Preencher os campos do formulário
Funcionário -> Funcionário: Validar os campos preenchidos
Funcionário -> Sistema: Atualizar o requerimento
Sistema -> BancodeDados: Atualizar o requerimento
Sistema -> Funcionário: Exibir mensagem de confirmação de edição
== ==


==Realizar baixa de requerimento==
Funcionário -> Sistema: Clicar na opção dar baixa
Sistema -> BancodeDados: Verificar registros de requerimentos
Sistema -> Funcionário: Exibir lista de requerimentos registrados
Funcionário -> Funcionário: Selecionar requerimento a ser dado baixa
Funcionário -> Funcionário: Digitar sua matrícula
Funcionário -> Funcionário: Escrever mensagem de retorno
Funcionário -> Funcionário: Selecionar opção "FINALIZADO"
Funcionário -> Sistema: Registrar requerimento como pendente
Sistema -> BancodeDados: Atualizar status do requerimento
Sistema -> Funcionário: Exibir mensagem de confirmação de baixa
== ==

@enduml
