app = "servicepro"

kill_signal = "SIGINT"
kill_timeout = 5

[[services]]
internal_port = 8080
protocol = "tcp"

[[services.tcp_checks]]
interval = 10000
timeout = 2000

[[services]]
internal_port = 5432
protocol = "tcp"
script_checks = ["pg_isready", "-q", "-h", "postgres-db", "-U", "postgres"]

[[services]]
internal_port = 5672
protocol = "tcp"
script_checks = ["rabbitmq-diagnostics", "ping"]
