name: Deploy ServicePro system
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build project
        run: mvn clean install -DskipTests
      - name: Login dockerhub
        run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_PASSWORD}}
      - name: Build docker image
        run: docker build -t ruanfonseca/serviceproimg:latest .
      - name: Push image docker
        run:  docker push ruanfonseca/serviceproimg:latest