name: Deploy ServicePro system

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17.0.9'

      - name: Build project
        run: mvn clean install -DskipTests

      - name: Login dockerhub
        run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Build docker image
        run: |
          docker build -t ruanfonseca/serviceproimg:latest .
          docker push ruanfonseca/serviceproimg:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull ruanfonseca/serviceproimg:latest

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Clone Docker Compose file
        run: git clone https://github.com/Sistema_servicePro/raw.git

      - name: Change directory
        run: cd raw

      - name: Run Docker Compose
        run: |
          sudo docker-compose up -d
