# Use a imagem base do PostgreSQL
FROM postgres:latest

# Configuração do banco de dados
ENV POSTGRES_DB nome-do-banco
ENV POSTGRES_USER usuario
ENV POSTGRES_PASSWORD senha

# Copia os scripts SQL para inicialização do banco de dados
COPY init.sql /docker-entrypoint-initdb.d/

# Exponha a porta que o PostgreSQL está utilizando
EXPOSE 5432
