# Use a imagem base do OpenJDK
FROM openjdk:11-jre-slim

# Define o diretório de trabalho
WORKDIR /app

# Copia o arquivo JAR da sua aplicação para o contêiner
COPY target/sua-aplicacao.jar /app/app.jar

# Exponha a porta que a aplicação Spring Boot está utilizando
EXPOSE 8080

# Comando para iniciar a aplicação quando o contêiner for iniciado
CMD ["java", "-jar", "app.jar"]
